### ISSUE TITLE
Install as documented does not work

### ISSUE THREAD

**Issue by wturnerharris** [barrel/barrel-cli#2]
Attempting a fresh install with `npm i barrel-cli -D` on the theme...

```
npm ERR! code E404
npm ERR! 404 Not Found: barrel-cli@latest
```

The log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'barrel-cli',
1 verbose cli   '-D' ]
2 info using npm@5.5.1
3 info using node@v8.9.2
4 verbose npm-session 8a5e40f2850f724d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/barrel-cli 860ms
8 silly fetchPackageMetaData error for barrel-cli@latest 404 Not Found: barrel-cli@latest
9 verbose stack Error: 404 Not Found: barrel-cli@latest
9 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd /Users/westurner/Sites/barrel-kb/wp-content/themes/barrel-base
11 verbose Darwin 16.7.0
12 verbose argv "/usr/local/Cellar/node/8.9.2/bin/node" "/usr/local/bin/npm" "i" "barrel-cli" "-D"
13 verbose node v8.9.2
14 verbose npm  v5.5.1
15 error code E404
16 error 404 Not Found: barrel-cli@latest
17 verbose exit [ 1, true ]
```

**Comment by maxrolon** [comment]
Updated this to @barrelny/cli. Please try again
